on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: installing dependencies
        run: npm install
      - name: running lint
        run: npx eslint

